### ISSUE TITLE
center .vox assets

### ISSUE THREAD

**Issue by madjin** [M3-org/loot-assets#1]
![image](https://user-images.githubusercontent.com/32600939/143714229-1cfc6fde-88a8-4345-a442-e1a877f1c152.png)

move and save vox assets to center, better turntable previews and equipping that way

**Comment by madjin** [comment]
going to take transparent png screenshots while doing this

![t_chain-mail-vox](https://user-images.githubusercontent.com/32600939/143718616-f0d2ebb5-fe3e-4b5b-9a2a-d140bb96a77f.png)
![t_demon-husk-vox](https://user-images.githubusercontent.com/32600939/143718623-92847ed9-1de5-4fab-8153-a890e94e60e9.png)

**Comment by avaer** [comment]
Looking awesome.

**Comment by madjin** [comment]
done and pushed
